apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakegame
  labels:
    app: snakegame

spec:
  replicas: 1

  selector:
    matchLabels:
      app: snakegame

  template:
    metadata:
      labels:
        app: snakegame

    spec:
      containers:
      - name: snakegame
        image: shivasai21/snakegame:vnc-v3
        imagePullPolicy: Always

        ports:
        - containerPort: 5900

        env:
        - name: DISPLAY
          value: ":99"

        - name: XDG_RUNTIME_DIR
          value: "/tmp"

---
apiVersion: v1
kind: Service
metadata:
  name: snakegame

spec:
  selector:
    app: snakegame

  type: LoadBalancer

  ports:
  - protocol: TCP
    port: 5900
    targetPort: 5900
