apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakegame
  namespace: default
  labels:
    app: snakegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snakegame
  template:
    metadata:
      labels:
        app: snakegame
    spec:
      containers:
      - name: snakegame
        image: shivasai21/snakegame:web-v2  # web-enabled image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: snakegame
  namespace: default
  labels:
    app: snakegame
spec:
  type: LoadBalancer
  selector:
    app: snakegame
  ports:
  - protocol: TCP
    port: 80        # external port
    targetPort: 5000 # forwards to container port
